# Generated by Django 4.0.6 on 2022-07-30 19:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_account_alter_wallet_customer_transaction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_issued', models.DateTimeField(default=django.utils.timezone.now)),
                ('card_name', models.CharField(max_length=15, null=True)),
                ('card_number', models.IntegerField()),
                ('card_type', models.CharField(max_length=15, null=True)),
                ('expire_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('card_status', models.CharField(max_length=15, null=True)),
                ('security_code', models.IntegerField()),
                ('issuer', models.CharField(max_length=15, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Card_account', to='wallet.account')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Card_wallet', to='wallet.wallet')),
            ],
        ),
    ]
