# Generated by Django 4.0.6 on 2022-07-31 06:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thirdparty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, null=True)),
                ('thirdparty_id', models.IntegerField()),
                ('phone_number', models.IntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Thirdparty_account', to='wallet.account')),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_type', models.CharField(max_length=15, null=True)),
                ('receipt_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('receipt_file', models.FileField(upload_to='')),
                ('total_amount', models.IntegerField()),
                ('account_number', models.IntegerField()),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Receipt_transaction', to='wallet.account')),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notifications_id', models.IntegerField()),
                ('name', models.CharField(max_length=15, null=True)),
                ('status', models.CharField(max_length=15, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Notifications_receipt', to='wallet.thirdparty')),
            ],
        ),
    ]
