# Generated by Django 4.0.6 on 2022-07-31 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0008_alter_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='symbol',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
