# Generated by Django 4.0.6 on 2022-07-31 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0009_currency_symbol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='Transaction_code',
        ),
    ]
