# Generated by Django 4.0.6 on 2022-08-01 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0010_remove_transaction_transaction_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currency',
            old_name='amont',
            new_name='amount',
        ),
    ]
