# Generated by Django 4.0.6 on 2022-08-19 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0012_alter_customer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='reward',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('o', 'Others')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='thirdparty',
            name='thirdparty_id',
            field=models.IntegerField(max_length=15, null=True),
        ),
    ]
