# Generated by Django 4.0.6 on 2022-08-22 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0013_alter_customer_gender_alter_reward_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='customer_id',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
