# Generated by Django 4.0.6 on 2022-08-25 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0014_alter_reward_customer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='account',
        ),
        migrations.RemoveField(
            model_name='card',
            name='wallet',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='guarantor',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='wallet',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='receipt',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='reward',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='thirdparty',
            name='account',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='destination_account',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='orign_account',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='receipt',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='wallet',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='customer',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='Card',
        ),
        migrations.DeleteModel(
            name='Currency',
        ),
        migrations.DeleteModel(
            name='Loan',
        ),
        migrations.DeleteModel(
            name='Notifications',
        ),
        migrations.DeleteModel(
            name='Receipt',
        ),
        migrations.DeleteModel(
            name='Reward',
        ),
        migrations.DeleteModel(
            name='Thirdparty',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
