# Generated by Django 4.0.6 on 2022-08-25 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0015_remove_card_account_remove_card_wallet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='employment',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='marital_status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
