# Generated by Django 4.0.6 on 2022-08-25 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0017_account_currency_wallet_transaction_thirdparty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='nationality',
            field=models.CharField(choices=[('T', 'Tanzania'), ('K', 'Kenya'), ('U', 'Uganda'), ('R', 'Rwanda'), ('S', 'Sudan'), ('O', 'Other countries')], max_length=15, null=True),
        ),
    ]
