# Generated by Django 4.0.6 on 2022-08-25 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0018_alter_customer_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='employment',
            field=models.CharField(choices=[('D', 'Doctor'), ('F', 'Farmer'), ('S', 'Student'), ('T', 'Teacher'), ('E', 'Engineer'), ('O', 'Others')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='marital_status',
            field=models.CharField(choices=[('M', 'Marriage'), ('S', 'Single'), ('O', 'Others')], max_length=20, null=True),
        ),
    ]
