# Generated by Django 4.0.6 on 2022-08-25 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0019_alter_customer_employment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='marital_status',
            field=models.CharField(choices=[('M', 'Marriage'), ('S', 'Single'), ('O', 'non-binary')], max_length=20, null=True),
        ),
    ]
