# Generated by Django 4.0.6 on 2022-08-25 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0020_alter_customer_marital_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', 'Non-binary')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='marital_status',
            field=models.CharField(choices=[('M', 'Marriage'), ('S', 'Single'), ('W', 'widowed'), ('D', 'Divorced')], max_length=20, null=True),
        ),
    ]
